# Use root/root as user/password credentials
version: '3.1'

services:

  ecommerce-db:
    image: mysql
    container_name:  mysql-deploy-composer
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33060:3306
    volumes:
      - ./data:/var/lib/mysql

  ecommerce-adminer:
    image: adminer
    container_name: adminer-deploy-composer
    restart: always
    ports:
      - 33070:8080
    depends_on:
      - ecommerce-db

      