spring:
    datasource:
        url: jdbc:mysql://localhost:33060/ecommerce?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        show-sql: true
        properties:        
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: create   
    data:
        rest:
            base-path: /api/rest
            
    flyway:
        enabled: false
            
server:
    port: 9999
    